source 'https://rubygems.org'

gem 'base64'
gem 'benchmark'
gem 'bigdecimal'
gem 'concurrent-ruby', '1.3.4'
gem 'debug'
gem 'haml', '~> 5'
gem 'logger'
gem 'middleman'
gem 'middleman-livereload'
gem 'middleman-sprockets'
gem 'mutex_m'
gem 'nokogiri'
gem 'rake'
gem 'redcarpet'
gem 'rss'
gem 'simple-rss'
