source 'https://rubygems.org'

gem 'concurrent-ruby', '1.3.4'
gem 'haml', '~> 5'
gem 'middleman'
gem 'middleman-livereload'
gem 'middleman-sprockets'
gem 'nokogiri'
gem 'rake'
gem 'redcarpet'
gem 'rubocop'
